# Generated by Django 5.2.1 on 2025-06-30 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_rater_studentcompletionreport_studentdataexplorer_and_more'),
        ('record', '0003_remove_recording_experiment_delete_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], default=1)),
                ('problem', models.BooleanField(default=False)),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='record.recording')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='login.session')),
            ],
        ),
    ]
