# Generated by Django 5.2.1 on 2025-06-30 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_id', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompletionReport',
            fields=[
            ],
            options={
                'verbose_name': 'Completion Report',
                'verbose_name_plural': 'Completion Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.student',),
        ),
        migrations.CreateModel(
            name='StudentDataExplorer',
            fields=[
            ],
            options={
                'verbose_name': 'Student Data Explorer',
                'verbose_name_plural': 'Student Data Explorer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.student',),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='login.student'),
        ),
        migrations.AddField(
            model_name='session',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='login.rater'),
        ),
    ]
