# Generated by Django 5.2.1 on 2025-05-22 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('record', '0003_remove_recording_experiment_delete_experiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='filename',
        ),
        migrations.AddField(
            model_name='activity',
            name='recording',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='record.recording'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('train_listen_ref', 'Listening to reference during training'), ('train_listen_own', 'Listening to own recording during training'), ('train_record', 'Training recording'), ('test_pre_record', 'Pre-training recording'), ('test_post_record', 'Post-training recording'), ('test_delay_record', 'Delayed post-training recording')], default='test_delay_record', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(default='', upload_to='audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='audio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='practice.audio'),
        ),
    ]
