# Generated by Django 5.2.1 on 2025-05-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_audio_filename_activity_recording_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
