# Generated by Django 5.2.1 on 2025-05-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('practice', '0003_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audios_for_practice', to='login.student'),
        ),
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('train_nat', 'Native speaker recording'), ('train_gs', 'Synthesized golden speaker')], default='train_gs', max_length=10),
        ),
    ]
