# Generated by Django 5.2.1 on 2025-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_audio_student_audio_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('test_nat', 'Pre-training native reference'), ('train_nat', 'Native speaker recording'), ('train_gs', 'Synthesized golden speaker')], default='train_gs', max_length=10),
        ),
    ]
