# Generated by Django 5.2.1 on 2025-05-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_audio_type'),
        ('record', '0003_remove_recording_experiment_delete_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='practice.audio'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='record.recording'),
        ),
    ]
