# Generated by Django 5.2.1 on 2025-06-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_activity_audio_alter_activity_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
