# Generated by Django 5.2.1 on 2025-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
