# Generated by Django 5.2.1 on 2025-05-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='experiments', to='login.session')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recordings', to='record.experiment')),
                ('original_audio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recordings', to='practice.audio')),
            ],
        ),
    ]
