# Generated by Django 5.2.1 on 2025-05-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='filename',
        ),
        migrations.AddField(
            model_name='recording',
            name='recorded_audio',
            field=models.FileField(default='', upload_to='recording/'),
            preserve_default=False,
        ),
    ]
